apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-node-service
spec:
  replicas: 5
  selector:
    app: kubia-service
  template:
    metadata:
      labels:
        app: kubia-service
    spec:
      containers:
      - name: kubia-service
        image: oloo/kubia
        ports:
        - containerPort: 8080
          protocol: TCP
